import type { Config } from "tailwindcss";

export default <Partial<Config>>{
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#93cdf5",
        "on-tertiary-fixed": "#001e2e",
        "primary-fixed-dim": "#fbb893",
        "on-primary-container": "#461f05",
        "on-primary-fixed": "#331200",
        "inverse-on-surface": "#31302f",
        "secondary-fixed": "#d7e2ff",
        surface: "#141312",
        "on-primary": "#4e250b",
        "secondary-fixed-dim": "#b7c7eb",
        "primary-fixed": "#ffdbc9",
        "on-tertiary-container": "#002d42",
        "surface-tint": "#fbb893",
        "on-secondary": "#20304e",
        "tertiary-fixed": "#c7e7ff",
        "on-background": "#e6e2df",
        "on-tertiary-fixed-variant": "#004c6c",
        "on-error": "#690005",
        "surface-container-highest": "#363433",
        "on-tertiary": "#00344c",
        "on-surface": "#e6e2df",
        background: "#141312",
        "inverse-surface": "#e6e2df",
        "surface-container": "#201f1e",
        secondary: "#b7c7eb",
        "primary-container": "#be8362",
        "on-primary-fixed-variant": "#693b1f",
        "on-secondary-fixed-variant": "#374765",
        "surface-container-high": "#2b2a29",
        "surface-container-lowest": "#0f0e0d",
        "on-surface-variant": "#d6c3b9",
        "on-secondary-container": "#a9b8dd",
        "surface-variant": "#363433",
        "surface-dim": "#141312",
        outline: "#9f8d85",
        "tertiary-container": "#5d97bd",
        "on-secondary-fixed": "#091b37",
        "surface-bright": "#3a3938",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#855234",
        tertiary: "#93cdf5",
        "secondary-container": "#3a4968",
        "surface-container-low": "#1c1b1a",
        "error-container": "#93000a",
        error: "#ffb4ab",
        "outline-variant": "#52443d",
        primary: "#fbb893",
      },
      fontFamily: {
        headline: ["Michroma", "Public Sans", "sans-serif"],
        display: ["Public Sans", "sans-serif"],
        body: ["Space Grotesk", "Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
};
